### ISSUE TITLE
missing package.json

### ISSUE THREAD

**Issue by pajamaw** [learn-co-students/angular-automated-transclusion-lab-v-000#17]
just noticed that all of the labs that i've been raising issues on are labs without -v-000 appended to the end. all of these labs (which is also teh path from raise an issue) have the package.json. 

the labs that the students fork, the labs with -v-000, do not have the package.json necessary to run the testing suite

**Comment by brennenawana** [comment]
Kindly merge pull request #62 to resolve this issue.

**Comment by theRingleman** [comment]
I am curious as to why these issues are being ignored?

**Comment by aturkewi** [comment]
Hey @theRingleman it's actually really hard for us to spot these issues here at Learn. We have a button in Learn to raise and issue and that actually raises the issue here: https://github.com/learn-co-curriculum/angular-automated-transclusion-lab

The reason is we copy this lab over for a bunch of different batches (v-000) being only one of them. So when we need to fix a lab, we want to fix the canonical version of it, not just a deploy. For that reason, we try to raise all issues on the canonical and it makes it hard for us to find all the issues on all the different deploys. 

One of the Learn Experts just found this issue here and we're working to get it fixed!

**Comment by aturkewi** [comment]
Closing issue here as it is being tracked on the canonical.
